# Promote content view and initiate patching of server
- hosts: "{{ servername }}"
  become: yes
  remote_user: rex
  serial: 1
  tasks: 
    - name: update server
      yum:
        name: '*' 
        state: latest

    
