---
# tasks file for change-banner
#
- name: Install test banner
  template:
    src: issue
    dest: /etc/issue
    owner: root
    group: root
    mode: 0644

- name: UIpdate banner for ssh
  lineinfile:
      dest: /etc/ssh/sshd_config
      regexp: "(?i)^#?Banner"
      line: Banner /etc/issue
      validate: /usr/sbin/sshd -tf %s
  notify: restart sshd
